version: "2"
services:
  front: # front-end server with NGINX and Polymer
    image: ageapps/docker-tubeterest-nginx
    ports:
      - "8080:80"
    depends_on:
      - back # depends resolving reverse-proxi hostname
  back: # back-end server with NodeJS that accesses DB
    image: ageapps/docker-tubeterest-node
    depends_on:
      - db
  db: # DB in MongoDB
    image: mongo
    command: mongod --smallfiles
    volumes:
      - ./database:/data # volume in host -> $(pwd)/database
